pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
            label 'MacNode'
        }
    }
    environment {
        Path = '/Users/admin/.nvm/versions/node/v8.11.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/admin/Library/Android/sdk/tools:/Users/admin/Library/Android/sdk/platform-tools'
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
